# Generated by Django 3.0.3 on 2020-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0002_auto_20200501_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
