# Generated by Django 3.0.3 on 2020-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0004_auto_20200501_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
