# Generated by Django 3.0.3 on 2020-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0005_auto_20200501_1259'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='_rating',
            field=models.IntegerField(default=0),
        ),
    ]
