# Generated by Django 3.0.3 on 2020-05-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0006_auto_20200501_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='_rating',
            new_name='rating',
        ),
    ]
